"""add_app_settings_table

Revision ID: d7e0bc2c8d4d
Revises: fed4031d5a4c
Create Date: 2025-07-07 21:57:47.810683

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd7e0bc2c8d4d'
down_revision: Union[str, None] = 'fed4031d5a4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('value_type', sa.String(length=20), nullable=True),
    sa.Column('display_name', sa.String(length=200), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('default_value', sa.Text(), nullable=True),
    sa.Column('allowed_values', sa.JSON(), nullable=True),
    sa.Column('min_value', sa.String(length=50), nullable=True),
    sa.Column('max_value', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=True),
    sa.Column('requires_restart', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_settings'))
    )
    op.create_index('idx_app_settings_category', 'app_settings', ['category'], unique=False)
    op.create_index('idx_app_settings_category_key', 'app_settings', ['category', 'key'], unique=True)
    op.create_index(op.f('ix_app_settings_id'), 'app_settings', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_app_settings_id'), table_name='app_settings')
    op.drop_index('idx_app_settings_category_key', table_name='app_settings')
    op.drop_index('idx_app_settings_category', table_name='app_settings')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
