// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCyOGiJLR-8JCvO6nCkdtm7q8CFkyEptDs',
    appId: '1:731680024116:web:0d98a09789e68102004c61',
    messagingSenderId: '731680024116',
    projectId: 'selm-7ca69',
    authDomain: 'selm-7ca69.firebaseapp.com',
    storageBucket: 'selm-7ca69.firebasestorage.app',
    measurementId: 'G-9NHQEP5Z76',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDDHehrVuv0CitHXAumQ5LgK1iu4cEVkgU',
    appId: '1:731680024116:android:059ab6cc13b549e3004c61',
    messagingSenderId: '731680024116',
    projectId: 'selm-7ca69',
    storageBucket: 'selm-7ca69.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDfuYYZrbZsG725EagVDbfMrqBaEKKxEE',
    appId: '1:731680024116:ios:7ea75a6fae76a70a004c61',
    messagingSenderId: '731680024116',
    projectId: 'selm-7ca69',
    storageBucket: 'selm-7ca69.firebasestorage.app',
    iosBundleId: 'com.selmapp.app',
  );
}
